#!/bin/bash
PATH=/bin
if [[ "$(uname -o 2>/dev/null)" != "Cygwin" ]] ; then
  echo "This script can only be used on Windows with CygWin !" >&2
  exit 1
fi
SRCDIR="$(dirname "$0")"
if [[ "$SRCDIR" = "." ]] ; then
  SRCDIR="$PWD"
fi
SDKROOTDIR="$SRCDIR/.."

# Please keep this list and list in make_native_client_sdk.sh synchronyzed
echo -n $': File is autogenerated and will be rewritten on the next "gclient sync".\r\n: If you want to change it please edit build_tools\\create_make_cmds.sh and\r\n: build_tools\\make_native_client_sdk.sh.\r\n@echo off\r\n\r\nsetlocal\r\n\r\nPATH=%~dp0..\\third_party\\cygwin\\bin;%PATH%\r\n\r\nmake.exe %*\r\n' > "$SDKROOTDIR/examples/make.cmd"
echo -n $': File is autogenerated and will be rewritten on the next "gclient sync".\r\n: If you want to change it please edit build_tools\\create_make_cmds.sh and\r\n: build_tools\\make_native_client_sdk.sh.\r\n@echo off\r\n\r\nsetlocal\r\n\r\nPATH=%~dp0..\\..\\third_party\\cygwin\\bin;%PATH%\r\n\r\nmake.exe %*\r\n' > "$SDKROOTDIR/examples/hello_world/make.cmd"
echo -n $': File is autogenerated and will be rewritten on the next "gclient sync".\r\n: If you want to change it please edit build_tools\\create_make_cmds.sh and\r\n: build_tools\\make_native_client_sdk.sh.\r\n@echo off\r\n\r\nsetlocal\r\n\r\nPATH=%~dp0..\\..\\third_party\\cygwin\\bin;%PATH%\r\n\r\nmake.exe %*\r\n' > "$SDKROOTDIR/examples/pi_generator/make.cmd"
echo -n $': File is autogenerated and will be rewritten on the next "gclient sync".\r\n: If you want to change it please edit build_tools\\create_make_cmds.sh and\r\n: build_tools\\make_native_client_sdk.sh.\r\n@echo off\r\n\r\nsetlocal\r\n\r\nPATH=%~dp0..\\..\\third_party\\cygwin\\bin;%PATH%\r\n\r\nmake.exe %*\r\n' > "$SDKROOTDIR/examples/sine_synth/make.cmd"
# TODO(NaCl SDK team): Put Tumbler back in once it's ported.
# echo -n $': File is autogenerated and will be rewritten on the next "gclient sync".\r\n: If you want to change it please edit build_tools\\create_make_cmds.sh and\r\n: build_tools\\make_native_client_sdk.sh.\r\n@echo off\r\n\r\nsetlocal\r\n\r\nPATH=%~dp0..\\..\\third_party\\cygwin\\bin;%PATH%\r\n\r\nmake.exe %*\r\n' > "$SDKROOTDIR/examples/tumbler/make.cmd"
