application: nacl-gallery
version: 5
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /games/*
  static_files: static/games/index.html
  upload: static/games/index.html
- url: /(.+\.(nmf|nexe))
  static_files: static/\1
  upload: static/(.+\.(nmf|nexe))
  mime_type: application/x-nacl
- url: /(.+)
  static_files: static/\1
  upload: static/(.+)
