application: nacl-gallery
version: 7
runtime: python
api_version: 1

# Skip files associated with Chrome Web Store uploading
# Note: We have to include the default skips or else it gets overridden
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*/cws/.*

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /(.+\.(nmf|nexe))
  static_files: static/\1
  upload: static/(.+\.(nmf|nexe))
  mime_type: application/x-nacl
- url: /(.+)
  static_files: static/\1
  upload: static/(.+)
