//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Project {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VisualStudio_Project {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisualStudio_Project() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Project.VisualStudio.Project", typeof(VisualStudio_Project).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reference.
        /// </summary>
        public static string AddReferenceDialogTitle {
            get {
                return ResourceManager.GetString("AddReferenceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add file &apos;{0}&apos; to project as project is null..
        /// </summary>
        public static string AddToNullProjectError {
            get {
                return ResourceManager.GetString("AddToNullProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load attribute &apos;{0}&apos; from project file &apos;{1}&apos;..
        /// </summary>
        public static string AttributeLoad {
            get {
                return ResourceManager.GetString("AttributeLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Action.
        /// </summary>
        public static string BuildAction {
            get {
                return ResourceManager.GetString("BuildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the file relates to the build and deployment process.
        /// </summary>
        public static string BuildActionDescription {
            get {
                return ResourceManager.GetString("BuildActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string BuildCaption {
            get {
                return ResourceManager.GetString("BuildCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception was thrown during BuildBegin event\n{0}.
        /// </summary>
        public static string BuildEventError {
            get {
                return ResourceManager.GetString("BuildEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbosity.
        /// </summary>
        public static string BuildVerbosity {
            get {
                return ResourceManager.GetString("BuildVerbosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify how much information is included in the build output.
        /// </summary>
        public static string BuildVerbosityDescription {
            get {
                return ResourceManager.GetString("BuildVerbosityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command you are attempting cannot be completed because the file &apos;{0}&apos; that must be modified cannot be changed. If the file is under source control, you may want to check it out; if the file is read-only on disk, you may want to change its attributes..
        /// </summary>
        public static string CancelQueryEdit {
            get {
                return ResourceManager.GetString("CancelQueryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with name &apos;{0}&apos; already exists and is open in an editor. Please give a unique name to the item you are adding, or delete the existing item first..
        /// </summary>
        public static string CannotAddFileThatIsOpenInEditor {
            get {
                return ResourceManager.GetString("CannotAddFileThatIsOpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save &apos;{0}&apos; as it is not open in the editor..
        /// </summary>
        public static string CanNotSaveFileNotOpeneInEditor {
            get {
                return ResourceManager.GetString("CanNotSaveFileNotOpeneInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECMA-335 CLI compatible framework (location must be provided).
        /// </summary>
        public static string cli1 {
            get {
                return ResourceManager.GetString("cli1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you change a file name extension, the file may become unusable. Are you sure you want to change it?.
        /// </summary>
        public static string ConfirmExtensionChange {
            get {
                return ResourceManager.GetString("ConfirmExtensionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Local.
        /// </summary>
        public static string CopyToLocal {
            get {
                return ResourceManager.GetString("CopyToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the reference will be copied to the output directory..
        /// </summary>
        public static string CopyToLocalDescription {
            get {
                return ResourceManager.GetString("CopyToLocalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tool.
        /// </summary>
        public static string CustomTool {
            get {
                return ResourceManager.GetString("CustomTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the tool that transforms a file at design time and places the output of that transformation into another file. For example, a dataset (.xsd) file comes with a default custom tool..
        /// </summary>
        public static string CustomToolDescription {
            get {
                return ResourceManager.GetString("CustomToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tool Namespace.
        /// </summary>
        public static string CustomToolNamespace {
            get {
                return ResourceManager.GetString("CustomToolNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace into which the output of the custom tool is placed..
        /// </summary>
        public static string CustomToolNamespaceDescription {
            get {
                return ResourceManager.GetString("CustomToolNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed.
        /// </summary>
        public static string Detailed {
            get {
                return ResourceManager.GetString("Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An &apos;Import&apos; of the file &apos;{1}&apos; was found in the project file &apos;{0}&apos;. This file is not registered as a safe file to import, and could contain targets and tasks that are harmful.  If this imported file is indeed considered safe, then it can be registered by writing to the registry key {2}..
        /// </summary>
        public static string DetailsImport {
            get {
                return ResourceManager.GetString("DetailsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more items named &apos;{1}&apos; were found in the project file &apos;{0}&apos;. These items normally should not be specified in the project file. They can change the way targets and tasks are executed during project load, and this could have harmful effects..
        /// </summary>
        public static string DetailsItem {
            get {
                return ResourceManager.GetString("DetailsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item referring to the file &apos;{1}&apos; was found in the project file &apos;{0}&apos;.  Since this file is located within a system directory, root directory, or network share, it could be harmful to write to this file..
        /// </summary>
        public static string DetailsItemLocation {
            get {
                return ResourceManager.GetString("DetailsItemLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property named &apos;{1}&apos; was found in the project file &apos;{0}&apos;.  This property normally should not be specified in the project file.  Its value can change the way targets and tasks are executed during project load, and this could have harmful effects..
        /// </summary>
        public static string DetailsProperty {
            get {
                return ResourceManager.GetString("DetailsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;Target&apos; named &apos;{1}&apos; was found in the project file &apos;{0}&apos;.  The tasks within this target could contain arbitrary code and may get executed as soon as the project is loaded in the IDE..
        /// </summary>
        public static string DetailsTarget {
            get {
                return ResourceManager.GetString("DetailsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An &apos;Import&apos; of the file &apos;{1}&apos; was found in the user project file &apos;{0}&apos;.  All imports in user project files are considered unsafe..
        /// </summary>
        public static string DetailsUserImport {
            get {
                return ResourceManager.GetString("DetailsUserImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;UsingTask&apos; tag which registers the &apos;{1}&apos; task was found in the project file &apos;{0}&apos;.  &apos;UsingTask&apos; tags in the project file take precedence over those in the imported .TARGETS files, and therefore could be used to execute arbitrary code during an otherwise unmodified build process..
        /// </summary>
        public static string DetailsUsingTask {
            get {
                return ResourceManager.GetString("DetailsUsingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic.
        /// </summary>
        public static string Diagnostic {
            get {
                return ResourceManager.GetString("Diagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory already exists.
        /// </summary>
        public static string DirectoryExistError {
            get {
                return ResourceManager.GetString("DirectoryExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening specified view &apos;{0}&apos; using editor &apos;{1}&apos;.
        /// </summary>
        public static string EditorViewError {
            get {
                return ResourceManager.GetString("EditorViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded Resource.
        /// </summary>
        public static string EmbeddedResource {
            get {
                return ResourceManager.GetString("EmbeddedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and folders cannot be:
        ///- Empty strings 
        ///- System reserved names, including &apos;CON&apos;, &apos;AUX&apos;, PRN&apos;, &apos;COM1&apos; or &apos;LPT2&apos; 
        ///- contain only &apos;.&apos;
        ///- have any of the following characters: / ? : &amp;  \ * &quot; &lt; &gt; | # %.
        /// </summary>
        public static string ErrorInvalidFileName {
            get {
                return ResourceManager.GetString("ErrorInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you provided is not a valid project name..
        /// </summary>
        public static string ErrorInvalidProjectName {
            get {
                return ResourceManager.GetString("ErrorInvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBuild path not found in registry. Please reinstall to fix the problem..
        /// </summary>
        public static string ErrorMsBuildRegistration {
            get {
                return ResourceManager.GetString("ErrorMsBuildRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to {0} could not be added. Please make sure that the file is accessible, and that it is a valid assembly or COM component..
        /// </summary>
        public static string ErrorReferenceCouldNotBeAdded {
            get {
                return ResourceManager.GetString("ErrorReferenceCouldNotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving File.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Application.
        /// </summary>
        public static string Exe {
            get {
                return ResourceManager.GetString("Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting object of type {0}..
        /// </summary>
        public static string ExpectedObjectOfType {
            get {
                return ResourceManager.GetString("ExpectedObjectOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve MSBuild property {0} from the project file..
        /// </summary>
        public static string FailedToRetrieveProperties {
            get {
                return ResourceManager.GetString("FailedToRetrieveProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name &apos;{0}&apos; already exists. Do you want to overwrite it?.
        /// </summary>
        public static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name &apos;{0}&apos; already exists..
        /// </summary>
        public static string FileAlreadyExistsAndCannotBeRenamed {
            get {
                return ResourceManager.GetString("FileAlreadyExistsAndCannotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination File Exists.
        /// </summary>
        public static string FileAlreadyExistsCaption {
            get {
                return ResourceManager.GetString("FileAlreadyExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file of this name is already part of the project. Do you want to overwrite it?.
        /// </summary>
        public static string FileAlreadyInProject {
            get {
                return ResourceManager.GetString("FileAlreadyInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination File Exists.
        /// </summary>
        public static string FileAlreadyInProjectCaption {
            get {
                return ResourceManager.GetString("FileAlreadyInProjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file or folder with the name &apos;{0}&apos; already exists on disk at this location. Please choose another name..
        /// </summary>
        public static string FileCannotBeRenamedToAnExistingFile {
            get {
                return ResourceManager.GetString("FileCannotBeRenamedToAnExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Copying File.
        /// </summary>
        public static string FileCopyError {
            get {
                return ResourceManager.GetString("FileCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File and folder names cannot contain a leading period..
        /// </summary>
        public static string FileNameCannotContainALeadingPeriod {
            get {
                return ResourceManager.GetString("FileNameCannotContainALeadingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file or folder.
        /// </summary>
        public static string FileNameDescription {
            get {
                return ResourceManager.GetString("FileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file or folder with the name &apos;{0}&apos; already exists on disk at this location. Please choose another name..
        /// </summary>
        public static string FileOrFolderAlreadyExists {
            get {
                return ResourceManager.GetString("FileOrFolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item &apos;{0}&apos; cannot be found on disk, either because it has been renamed, deleted, or moved to a new location..
        /// </summary>
        public static string FileOrFolderCannotBeFound {
            get {
                return ResourceManager.GetString("FileOrFolderCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Properties.
        /// </summary>
        public static string FileProperties {
            get {
                return ResourceManager.GetString("FileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of this folder.
        /// </summary>
        public static string FolderNameDescription {
            get {
                return ResourceManager.GetString("FolderNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Properties.
        /// </summary>
        public static string FolderProperties {
            get {
                return ResourceManager.GetString("FolderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path.
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the file.
        /// </summary>
        public static string FullPathDescription {
            get {
                return ResourceManager.GetString("FullPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation object invalid..
        /// </summary>
        public static string InvalidAutomationObject {
            get {
                return ResourceManager.GetString("InvalidAutomationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid logger type\nExpected: {0}\nReceived: {1}.
        /// </summary>
        public static string InvalidLoggerType {
            get {
                return ResourceManager.GetString("InvalidLoggerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidParameter.
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item &apos;{0}&apos; does not exist in the project directory. It may have been moved, renamed or deleted..
        /// </summary>
        public static string ItemDoesNotExistInProjectDirectory {
            get {
                return ResourceManager.GetString("ItemDoesNotExistInProjectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save &apos;{0}&apos; outside the project directory. Linked items are not supported..
        /// </summary>
        public static string LinkedItemsAreNotSupported {
            get {
                return ResourceManager.GetString("LinkedItemsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal.
        /// </summary>
        public static string Minimal {
            get {
                return ResourceManager.GetString("Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nested project has failed to reload..
        /// </summary>
        public static string NestedProjectFailedToReload {
            get {
                return ResourceManager.GetString("NestedProjectFailedToReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Output.
        /// </summary>
        public static string OutputBuilt {
            get {
                return ResourceManager.GetString("OutputBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the DLL or EXE built by the project..
        /// </summary>
        public static string OutputBuiltDescription {
            get {
                return ResourceManager.GetString("OutputBuiltDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Files.
        /// </summary>
        public static string OutputContentFiles {
            get {
                return ResourceManager.GetString("OutputContentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains all content files in the project..
        /// </summary>
        public static string OutputContentFilesDescription {
            get {
                return ResourceManager.GetString("OutputContentFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Files.
        /// </summary>
        public static string OutputDocumentation {
            get {
                return ResourceManager.GetString("OutputDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the XML Documentation files for the project..
        /// </summary>
        public static string OutputDocumentationDescription {
            get {
                return ResourceManager.GetString("OutputDocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized Resources.
        /// </summary>
        public static string OutputLocalizedResourceDlls {
            get {
                return ResourceManager.GetString("OutputLocalizedResourceDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the satellite assemblies for each culture&apos;s resources..
        /// </summary>
        public static string OutputLocalizedResourceDllsDescription {
            get {
                return ResourceManager.GetString("OutputLocalizedResourceDllsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path.
        /// </summary>
        public static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the primary output.
        /// </summary>
        public static string OutputPathDescription {
            get {
                return ResourceManager.GetString("OutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Files.
        /// </summary>
        public static string OutputSourceFiles {
            get {
                return ResourceManager.GetString("OutputSourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains all source files in the project..
        /// </summary>
        public static string OutputSourceFilesDescription {
            get {
                return ResourceManager.GetString("OutputSourceFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Symbols.
        /// </summary>
        public static string OutputSymbols {
            get {
                return ResourceManager.GetString("OutputSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the debugging files for the project..
        /// </summary>
        public static string OutputSymbolsDescription {
            get {
                return ResourceManager.GetString("OutputSymbolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Serialization Assemblies.
        /// </summary>
        public static string OutputXmlSerializer {
            get {
                return ResourceManager.GetString("OutputXmlSerializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the XML serialization assemblies for the project..
        /// </summary>
        public static string OutputXmlSerializerDescription {
            get {
                return ResourceManager.GetString("OutputXmlSerializerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterCannotBeNullOEmpty.
        /// </summary>
        public static string ParameterCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ParameterCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be a valid guid..
        /// </summary>
        public static string ParameterMustBeAValidGuid {
            get {
                return ResourceManager.GetString("ParameterMustBeAValidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must be a valid item identifier..
        /// </summary>
        public static string ParameterMustBeAValidItemId {
            get {
                return ResourceManager.GetString("ParameterMustBeAValidItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not available or corrupted and thus cannot be pasted..
        /// </summary>
        public static string PasteFailed {
            get {
                return ResourceManager.GetString("PasteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complete path to &apos;{0}&apos; exceeds the maximum number of characters permitted by the file system..
        /// </summary>
        public static string PathTooLong {
            get {
                return ResourceManager.GetString("PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to library &apos;{0}&apos; cannot be added. Adding this project as a reference would cause a circular dependency. .
        /// </summary>
        public static string ProjectContainsCircularReferences {
            get {
                return ResourceManager.GetString("ProjectContainsCircularReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File.
        /// </summary>
        public static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file containing build, configuration, and other information about the project..
        /// </summary>
        public static string ProjectFileDescription {
            get {
                return ResourceManager.GetString("ProjectFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Folder.
        /// </summary>
        public static string ProjectFolder {
            get {
                return ResourceManager.GetString("ProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absolute location of the project..
        /// </summary>
        public static string ProjectFolderDescription {
            get {
                return ResourceManager.GetString("ProjectFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project location is not trusted:{0}{0}{1}{0}{0}Running the application may result in security exceptions when it {0}attempts to perform actions which require full trust.{0}{0}Click OK to ignore and continue..
        /// </summary>
        public static string ProjectLocationNotTrusted {
            get {
                return ResourceManager.GetString("ProjectLocationNotTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Properties.
        /// </summary>
        public static string ProjectProperties {
            get {
                return ResourceManager.GetString("ProjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file &apos;{0}&apos; has been modified outside of Visual Studio.  Do you want to reload the project?.
        /// </summary>
        public static string QueryReloadNestedProject {
            get {
                return ResourceManager.GetString("QueryReloadNestedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet.
        /// </summary>
        public static string Quiet {
            get {
                return ResourceManager.GetString("Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to component &apos;{0}&apos; cannot be added. A reference to the component already exists in the project..
        /// </summary>
        public static string ReferenceAlreadyExists {
            get {
                return ResourceManager.GetString("ReferenceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Properties.
        /// </summary>
        public static string ReferenceProperties {
            get {
                return ResourceManager.GetString("ReferenceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string ReferencesNodeName {
            get {
                return ResourceManager.GetString("ReferencesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Name).
        /// </summary>
        public static string RefName {
            get {
                return ResourceManager.GetString("RefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name of the reference.
        /// </summary>
        public static string RefNameDescription {
            get {
                return ResourceManager.GetString("RefNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename directory failed. {0}.
        /// </summary>
        public static string RenameFolder {
            get {
                return ResourceManager.GetString("RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTL_False.
        /// </summary>
        public static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        public static string SaveCaption {
            get {
                return ResourceManager.GetString("SaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save modified documents?.
        /// </summary>
        public static string SaveModifiedDocuments {
            get {
                return ResourceManager.GetString("SaveModifiedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file can only be saved into the project location &apos;{0}&apos;..
        /// </summary>
        public static string SaveOfProjectFileOutsideCurrentDirectory {
            get {
                return ResourceManager.GetString("SaveOfProjectFileOutsideCurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening specified view &apos;{0}&apos; using standard editor..
        /// </summary>
        public static string StandardEditorViewError {
            get {
                return ResourceManager.GetString("StandardEditorViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to use an item that has already been deleted or that does not exist..
        /// </summary>
        public static string UseOfDeletedItemError {
            get {
                return ResourceManager.GetString("UseOfDeletedItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft .Net Framework v1.0.
        /// </summary>
        public static string v1 {
            get {
                return ResourceManager.GetString("v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft .Net Framework v1.1.
        /// </summary>
        public static string v11 {
            get {
                return ResourceManager.GetString("v11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft .Net Framework v2.0.
        /// </summary>
        public static string v2 {
            get {
                return ResourceManager.GetString("v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Application.
        /// </summary>
        public static string WinExe {
            get {
                return ResourceManager.GetString("WinExe", resourceCulture);
            }
        }
    }
}
