// Copyright (c) 2011 The Native Client Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows.Forms;
using Google.NaClVsx.DebugSupport;
using Google.NaClVsx.DebugSupport.DWARF;
using Microsoft.VisualStudio;
using Microsoft.Win32;
using NaClVsx;

namespace SymbolDBViewer
{
  partial class NexeLoader
  {
    /// <summary>
    ///   Required designer variable.  Most of the contents of this file are
    ///   generated by the VS Design GUI and are not to be modified.  
    /// </summary>
    private System.ComponentModel.IContainer components = null;

    /// <summary>
    ///   Clean up any resources being used.
    /// </summary>
    /// <param name="disposing">true if managed resources should be disposed;
    /// otherwise, false.</param>
    protected override void Dispose(bool disposing) {
      if (disposing && (components != null)) {
        components.Dispose();
      }
      base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    /// <summary>
    ///   Required method for Designer support - do not modify
    ///   the contents of this method with the code editor.
    /// </summary>
    private void InitializeComponent() {
      this.nexeChooserDialog_ = new System.Windows.Forms.OpenFileDialog();
      this.symbolDbTreeView_ = new System.Windows.Forms.TreeView();
      this.loadStatusStrip_ = new System.Windows.Forms.StatusStrip();
      this.statusLabel_ = new System.Windows.Forms.ToolStripStatusLabel();
      this.loadButton_ = new System.Windows.Forms.Button();
      this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
      this.fileNameLabel_ = new System.Windows.Forms.Label();
      this.searchTextBox_ = new System.Windows.Forms.TextBox();
      this.searchButton_ = new System.Windows.Forms.Button();
      this.collapseAllButton_ = new System.Windows.Forms.Button();
      this.searchNavBackButton_ = new System.Windows.Forms.Button();
      this.searchNavLabel_ = new System.Windows.Forms.Label();
      this.searchNavForwardButton_ = new System.Windows.Forms.Button();
      this.dieLoader_ = new SymbolDBViewer.DIELoader();
      this.fileLoader_ = new SymbolDBViewer.SourceFileLoader();
      this.locationLoader_ = new SymbolDBViewer.SourceLocationLoader();
      this.scopeTransitionLoader_ = new SymbolDBViewer.ScopeTransitionLoader();
      this.callFrameLoader_ = new SymbolDBViewer.CallFrameLoader();
      this.locListLoader_ = new SymbolDBViewer.LocListLoader();
      this.loadStatusStrip_.SuspendLayout();
      this.flowLayoutPanel1.SuspendLayout();
      this.SuspendLayout();
      // 
      // nexeChooserDialog_
      // 
      this.nexeChooserDialog_.FileName = "openFileDialog1";
      // 
      // symbolDbTreeView_
      // 
      this.symbolDbTreeView_.Dock = System.Windows.Forms.DockStyle.Fill;
      this.symbolDbTreeView_.Location = new System.Drawing.Point(0, 29);
      this.symbolDbTreeView_.Name = "symbolDbTreeView_";
      this.symbolDbTreeView_.Size = new System.Drawing.Size(756, 559);
      this.symbolDbTreeView_.TabIndex = 2;
      // 
      // loadStatusStrip_
      // 
      this.loadStatusStrip_.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.statusLabel_});
      this.loadStatusStrip_.Location = new System.Drawing.Point(0, 611);
      this.loadStatusStrip_.Name = "loadStatusStrip_";
      this.loadStatusStrip_.Size = new System.Drawing.Size(756, 22);
      this.loadStatusStrip_.TabIndex = 4;
      this.loadStatusStrip_.Text = "statusStrip1";
      // 
      // statusLabel_
      // 
      this.statusLabel_.Name = "statusLabel_";
      this.statusLabel_.Size = new System.Drawing.Size(48, 17);
      this.statusLabel_.Text = "Inactive";
      // 
      // loadButton_
      // 
      this.loadButton_.Dock = System.Windows.Forms.DockStyle.Bottom;
      this.loadButton_.Location = new System.Drawing.Point(0, 588);
      this.loadButton_.Name = "loadButton_";
      this.loadButton_.Size = new System.Drawing.Size(756, 23);
      this.loadButton_.TabIndex = 6;
      this.loadButton_.Text = "Load a Nexe";
      this.loadButton_.UseVisualStyleBackColor = true;
      this.loadButton_.Click += new System.EventHandler(this.HandleLoadButtonClick);
      // 
      // flowLayoutPanel1
      // 
      this.flowLayoutPanel1.AutoSize = true;
      this.flowLayoutPanel1.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
      this.flowLayoutPanel1.Controls.Add(this.fileNameLabel_);
      this.flowLayoutPanel1.Controls.Add(this.searchTextBox_);
      this.flowLayoutPanel1.Controls.Add(this.searchButton_);
      this.flowLayoutPanel1.Controls.Add(this.collapseAllButton_);
      this.flowLayoutPanel1.Controls.Add(this.searchNavBackButton_);
      this.flowLayoutPanel1.Controls.Add(this.searchNavLabel_);
      this.flowLayoutPanel1.Controls.Add(this.searchNavForwardButton_);
      this.flowLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Top;
      this.flowLayoutPanel1.Location = new System.Drawing.Point(0, 0);
      this.flowLayoutPanel1.Name = "flowLayoutPanel1";
      this.flowLayoutPanel1.Size = new System.Drawing.Size(756, 29);
      this.flowLayoutPanel1.TabIndex = 7;
      // 
      // fileNameLabel_
      // 
      this.fileNameLabel_.Anchor = System.Windows.Forms.AnchorStyles.Left;
      this.fileNameLabel_.AutoSize = true;
      this.fileNameLabel_.Location = new System.Drawing.Point(3, 8);
      this.fileNameLabel_.Name = "fileNameLabel_";
      this.fileNameLabel_.Size = new System.Drawing.Size(82, 13);
      this.fileNameLabel_.TabIndex = 2;
      this.fileNameLabel_.Text = "No nexe loaded";
      this.fileNameLabel_.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
      // 
      // searchTextBox_
      // 
      this.searchTextBox_.Location = new System.Drawing.Point(91, 3);
      this.searchTextBox_.Name = "searchTextBox_";
      this.searchTextBox_.Size = new System.Drawing.Size(100, 20);
      this.searchTextBox_.TabIndex = 3;
      // 
      // searchButton_
      // 
      this.searchButton_.Location = new System.Drawing.Point(197, 3);
      this.searchButton_.Name = "searchButton_";
      this.searchButton_.Size = new System.Drawing.Size(75, 23);
      this.searchButton_.TabIndex = 4;
      this.searchButton_.Text = "Search";
      this.searchButton_.UseVisualStyleBackColor = true;
      this.searchButton_.Click += new System.EventHandler(this.SearchButtonClick);
      // 
      // closeAllButton_
      // 
      this.collapseAllButton_.Location = new System.Drawing.Point(278, 3);
      this.collapseAllButton_.Name = "collapseAllButton_";
      this.collapseAllButton_.Size = new System.Drawing.Size(75, 23);
      this.collapseAllButton_.TabIndex = 5;
      this.collapseAllButton_.Text = "Close All";
      this.collapseAllButton_.UseVisualStyleBackColor = true;
      this.collapseAllButton_.Click += new System.EventHandler(this.CloseAllButtonClick);
      // 
      // searchNavBackButton_
      // 
      this.searchNavBackButton_.Location = new System.Drawing.Point(359, 3);
      this.searchNavBackButton_.Name = "searchNavBackButton_";
      this.searchNavBackButton_.Size = new System.Drawing.Size(75, 23);
      this.searchNavBackButton_.TabIndex = 6;
      this.searchNavBackButton_.Text = "<<";
      this.searchNavBackButton_.UseVisualStyleBackColor = true;
      this.searchNavBackButton_.Click += new System.EventHandler(this.SearchNavBackButtonClick);
      // 
      // searchNavLabel_
      // 
      this.searchNavLabel_.Anchor = System.Windows.Forms.AnchorStyles.Left;
      this.searchNavLabel_.AutoSize = true;
      this.searchNavLabel_.Location = new System.Drawing.Point(440, 8);
      this.searchNavLabel_.Name = "searchNavLabel_";
      this.searchNavLabel_.Size = new System.Drawing.Size(24, 13);
      this.searchNavLabel_.TabIndex = 7;
      this.searchNavLabel_.Text = "0/0";
      // 
      // searchNavForwardButton_
      // 
      this.searchNavForwardButton_.Location = new System.Drawing.Point(470, 3);
      this.searchNavForwardButton_.Name = "searchNavForwardButton_";
      this.searchNavForwardButton_.Size = new System.Drawing.Size(75, 23);
      this.searchNavForwardButton_.TabIndex = 8;
      this.searchNavForwardButton_.Text = ">>";
      this.searchNavForwardButton_.UseVisualStyleBackColor = true;
      this.searchNavForwardButton_.Click += new System.EventHandler(this.SearchNavForwardButtonClick);
      // 
      // dieLoader_
      // 
      this.dieLoader_.WorkerReportsProgress = true;
      this.dieLoader_.DoWork += new System.ComponentModel.DoWorkEventHandler(dieLoader_.PopulateTree);
      this.dieLoader_.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.UpdateTreeView);
      this.dieLoader_.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.PopulateNodesProgressChanged);
      // 
      // fileLoader_
      // 
      this.fileLoader_.WorkerReportsProgress = true;
      this.fileLoader_.DoWork += new System.ComponentModel.DoWorkEventHandler(fileLoader_.PopulateTree);
      this.fileLoader_.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.UpdateTreeView);
      this.fileLoader_.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.PopulateNodesProgressChanged);
      // 
      // locationLoader_
      // 
      this.locationLoader_.WorkerReportsProgress = true;
      this.locationLoader_.DoWork += new System.ComponentModel.DoWorkEventHandler(locationLoader_.PopulateTree);
      this.locationLoader_.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.UpdateTreeView);
      this.locationLoader_.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.PopulateNodesProgressChanged);
      // 
      // scopeTransitionLoader_
      // 
      this.scopeTransitionLoader_.WorkerReportsProgress = true;
      this.scopeTransitionLoader_.DoWork += new System.ComponentModel.DoWorkEventHandler(scopeTransitionLoader_.PopulateTree);
      this.scopeTransitionLoader_.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.UpdateTreeView);
      this.scopeTransitionLoader_.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.PopulateNodesProgressChanged);
      // 
      // callFrameLoader_
      // 
      this.callFrameLoader_.WorkerReportsProgress = true;
      this.callFrameLoader_.DoWork += new System.ComponentModel.DoWorkEventHandler(callFrameLoader_.PopulateTree);
      this.callFrameLoader_.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.UpdateTreeView);
      this.callFrameLoader_.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.PopulateNodesProgressChanged);
      // 
      // locListLoader_
      // 
      this.locListLoader_.WorkerReportsProgress = true;
      this.locListLoader_.DoWork += new System.ComponentModel.DoWorkEventHandler(locListLoader_.PopulateTree);
      this.locListLoader_.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.UpdateTreeView);
      this.locListLoader_.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.PopulateNodesProgressChanged);
      // 
      // NexeLoader
      // 
      this.AcceptButton = this.searchButton_;
      this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
      this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
      this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
      this.ClientSize = new System.Drawing.Size(756, 633);
      this.Controls.Add(this.symbolDbTreeView_);
      this.Controls.Add(this.flowLayoutPanel1);
      this.Controls.Add(this.loadButton_);
      this.Controls.Add(this.loadStatusStrip_);
      this.Name = "NexeLoader";
      this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show;
      this.Text = "SymbolDBViewer";
      this.loadStatusStrip_.ResumeLayout(false);
      this.loadStatusStrip_.PerformLayout();
      this.flowLayoutPanel1.ResumeLayout(false);
      this.flowLayoutPanel1.PerformLayout();
      this.ResumeLayout(false);
      this.PerformLayout();

    }

    #endregion


    /// <summary>
    ///   The actual symbol database, which can load a nexe.
    /// </summary>
    private SymbolDatabase symbolDatabase_;
    /// <summary>
    ///   A file chooser for the user to select a nexe.
    /// </summary>
    private OpenFileDialog nexeChooserDialog_;
    /// <summary>
    ///   The TreeView of the contents of symbolDatabase once it has finished
    ///   loading.
    /// </summary>
    private TreeView symbolDbTreeView_;
    /// <summary>
    ///   This is used for reporting load progress in case he/she wonders
    ///   what's taking so long.
    /// </summary>
    private StatusStrip loadStatusStrip_;
    /// <summary>
    ///   The button which fires the event that causes the nexe to be
    ///   selected and loaded.
    /// </summary>
    private Button loadButton_;
    /// <summary>
    ///   This is the label whose text will actually indicate load progress
    ///   and status.
    /// </summary>
    private ToolStripStatusLabel statusLabel_;
    /// <summary>
    ///   This is the text box where the user can type is search string.
    /// </summary>
    private TextBox searchTextBox_;
    /// <summary>
    ///   This button fires the event that starts the search.
    /// </summary>
    private Button searchButton_;
    /// <summary>
    ///   This background worker loads the DIE entries.
    /// </summary>
    private DIELoader dieLoader_;
    /// <summary>
    ///   This background workder laods the file entries.
    /// </summary>
    private SourceFileLoader fileLoader_;
    /// <summary>
    ///   This background worker loads the location entries.
    /// </summary>
    private SourceLocationLoader locationLoader_;
    /// <summary>
    ///   This background worker loads the scope transition entries.
    /// </summary>
    private ScopeTransitionLoader scopeTransitionLoader_;
    /// <summary>
    ///   This background workder loads the call frame entries.
    /// </summary>
    private CallFrameLoader callFrameLoader_;
    /// <summary>
    ///   This background worker loads the location list entries.
    /// </summary>
    private LocListLoader locListLoader_;
    /// <summary>
    ///   This layout helps with the buttons and labels anchored on the top of
    ///   the form.
    /// </summary>
    private FlowLayoutPanel flowLayoutPanel1;
    /// <summary>
    ///   This label displays the name of the nexe that is currently loaded
    ///   into the SymbolDBViewer.
    /// </summary>
    private Label fileNameLabel_;
    /// <summary>
    ///   This button collapses any opened nodes in the symbolDbTreeView_.
    /// </summary>
    private Button collapseAllButton_;
    /// <summary>
    ///   This button navigates down an entry in the search results.
    /// </summary>
    private Button searchNavBackButton_;
    /// <summary>
    ///   This label indicates which search result was most recently navigated
    ///   to.
    /// </summary>
    private Label searchNavLabel_;
    /// <summary>
    ///   This button navigates up an entry in the search results.
    /// </summary>
    private Button searchNavForwardButton_;
  }
}

